image:https://m-m-m.github.io/logo.svg[logo,width="150",link="https://m-m-m.github.io"]

image:https://img.shields.io/github/license/m-m-m/ui-android.svg?label=License["Apache License, Version 2.0",link=https://github.com/m-m-m/ui-android/blob/master/LICENSE]
image:https://github.com/m-m-m/ui-android/actions/workflows/build.yml/badge.svg["Build Status",link="https://github.com/m-m-m/ui-android/actions/workflows/build.yml"]

== mmm-ui-android

image:https://img.shields.io/maven-central/v/io.github.m-m-m/mmm-ui-android.svg?label=Maven%20Central["Maven Central",link=https://search.maven.org/search?q=g:io.github.m-m-m]
image:https://m-m-m.github.io/javadoc.svg?status=online["apidoc",link="https://m-m-m.github.io/docs/api/io.github.mmm.ui.android/module-summary.html"]

The module `mmm-ui-android` provides the implementation of the https://github.com/m-m-m/ui-api[mmm-ui-api] for android.
Please note that mobile devices (esp. phones) are very limited. In case you want to support mobile phones from the same UI codebase, you are strongly encouraged to do a `mobile first` approach. This means you start with developing and testing the mobile app. Later you add features to the UI what can be extended when there is more display space available.

=== Usage

Maven Dependency:
```xml
<dependency>
  <groupId>io.github.m-m-m</groupId>
  <artifactId>mmm-ui-android-all</artifactId>
</dependency>
```

Module Dependency:
```java
  requires transitive io.github.mmm.ui.android.all;
```

=== Status

The implementation of `mmm-ui-api` for android is still very incomplete. We need your help if you have android experience. To understand why our progress with android is very limited read link:../../wiki/android-sucks[this].
